# Generated by Django 4.0.3 on 2022-05-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_enumerations_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
    ]
