# Generated by Django 4.0.3 on 2022-05-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_files_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='group_id',
            new_name='group',
        ),
    ]
